export const HEADER_GETLIST = "header/getlist"
export const HEADER_CHANGEDNAV = "header/changenav"
export const HEADER_SETNAVCLASS = "header/setnavclass"
export const HEADER_NAVTOWCLICK = "header/navtwoclick"
export const HEADER_CLOSENAV = "header/HEADER_CLOSENAV"